// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using LibraFoto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraFoto.Data.Migrations
{
    [DbContext(typeof(LibraFotoDbContext))]
    [ExcludeFromCodeCoverage]
    partial class LibraFotoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("LibraFoto.Data.Entities.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CoverPhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoverPhotoId");

                    b.HasIndex("Name");

                    b.HasIndex("SortOrder");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.DisplaySettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageFit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shuffle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlideDuration")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Transition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("DisplaySettings");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.GuestLink", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentUploads")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxUploads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetAlbumId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TargetAlbumId");

                    b.ToTable("GuestLinks");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderFileId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateAdded");

                    b.HasIndex("DateTaken");

                    b.HasIndex("Filename");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId", "ProviderFileId")
                        .IsUnique();

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.PhotoAlbum", b =>
                {
                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("SortOrder");

                    b.ToTable("PhotoAlbums");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.PhotoTag", b =>
                {
                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.PickerSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MediaItemsSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PickerUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("PickerSessions");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.StorageProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Type");

                    b.ToTable("StorageProviders");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Album", b =>
                {
                    b.HasOne("LibraFoto.Data.Entities.Photo", "CoverPhoto")
                        .WithMany("CoverForAlbums")
                        .HasForeignKey("CoverPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoverPhoto");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.GuestLink", b =>
                {
                    b.HasOne("LibraFoto.Data.Entities.User", "CreatedBy")
                        .WithMany("CreatedGuestLinks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraFoto.Data.Entities.Album", "TargetAlbum")
                        .WithMany()
                        .HasForeignKey("TargetAlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("TargetAlbum");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Photo", b =>
                {
                    b.HasOne("LibraFoto.Data.Entities.StorageProvider", "Provider")
                        .WithMany("Photos")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.PhotoAlbum", b =>
                {
                    b.HasOne("LibraFoto.Data.Entities.Album", "Album")
                        .WithMany("PhotoAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraFoto.Data.Entities.Photo", "Photo")
                        .WithMany("PhotoAlbums")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.PhotoTag", b =>
                {
                    b.HasOne("LibraFoto.Data.Entities.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraFoto.Data.Entities.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.PickerSession", b =>
                {
                    b.HasOne("LibraFoto.Data.Entities.StorageProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Album", b =>
                {
                    b.Navigation("PhotoAlbums");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Photo", b =>
                {
                    b.Navigation("CoverForAlbums");

                    b.Navigation("PhotoAlbums");

                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.StorageProvider", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.Tag", b =>
                {
                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("LibraFoto.Data.Entities.User", b =>
                {
                    b.Navigation("CreatedGuestLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
